### ISSUE TITLE
Update your tool with the latest Website updates (if needed)

### ISSUE THREAD

**Issue by MythicalPlayz** [montylion/pretendo-locale-tester#4]

**Comment by limesdotpink** [comment]
I probably won't update this until there's a major change in the website (e.g. new strings to localize, a new page,...). Until then, this gets the job done imo.

P.S.: the only major feature that's missing is the locale switcher atm, but we don't need it here as the locale is provided by the user

**Comment by limesdotpink** [comment]
Updated since we're gonna add a localization page!
